# Generated by Django 5.2.7 on 2025-10-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=100)),
                ('drop_off_location', models.CharField(max_length=100)),
                ('current_cycle_used', models.FloatField()),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('total_duration', models.FloatField(blank=True, null=True)),
                ('route_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('stop_type', models.CharField(max_length=50)),
                ('duration', models.FloatField()),
                ('distance_from_start', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_stops', to='trips.trip')),
            ],
            options={
                'ordering': ['distance_from_start'],
            },
        ),
    ]
